spring.application.name=barberiapp-backend

# Servidor Port
server.port=8080

# Configuracion de Supabase Postgres
# Reemplaza [TU-PASSWORD] y el string por el connection string de tu panel en Supabase
# Settings -> Database -> Connection string -> JDBC -> check "Use connection pooling"
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.gynffmomjhkwelybppfd
spring.datasource.password=HolaMundo123izi.
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl-auto: validate/update/create/create-drop/none
# Usando 'update' para que Spring cree o actualice las tablas en Supabase
spring.jpa.hibernate.ddl-auto=update

# Mostrar comandos SQL (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
