spring.application.name=barberiapp-backend

# Servidor Port
server.port=8080

# Configuracion de Supabase Postgres
spring.datasource.url=jdbc:postgresql://db.pinbbhmkeibplimhlswn.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=HolaMundo123izi.
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=barbershop-super-secret-key-minimo-256-bits-para-seguridad-hmac-sha256
jwt.expiration=604800000